server:
  port: 8080
langchain4j:
  community:
    dashscope:
      streaming-chat-model:
        model-name: qwen-plus
        api-key: ${DASH_SCOPE_API_KEY}
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
  datasource:
    url: jdbc:mysql://localhost:3306/ai_app?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${DEV_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secretKey: "123456"
  ttlMillis: "432000000" # 5天
  tokenHead: "Bearer "